# Generated by Django 2.1.5 on 2021-11-27 17:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noyau', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netfeelex',
            name='Date_publie',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 27, 17, 49, 41, 420188), verbose_name='Date publié'),
        ),
    ]
