# Generated by Django 2.1.5 on 2021-11-27 17:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noyau', '0002_auto_20211127_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netfeelex',
            name='Date_publie',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 27, 17, 50, 29, 815207), verbose_name='Date publié'),
        ),
    ]
