# Generated by Django 2.1.5 on 2021-11-30 01:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noyau', '0004_auto_20211127_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netfeelex',
            name='Date_publie',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 30, 1, 23, 42, 557410), verbose_name='Date publié'),
        ),
    ]
